Clean local development instructions
Zenysis/Harmony pull request #112
Opened 2023-11-02 10:43 UTC by Sybrand

**Summary:**
In the process of creating clean, easy to follow instructions for local development, uncovered some hard coded variables that need adjusting when not running web & pipeline containerised.

**Test Plan:**
Run pipeline local and containerised - follow instructions from TBD for local.

2023-11-08 19:33 UTC, tahitihat requested changes
Wiki + README: I consider this an interim state — it's slightly confusing that the majority of the instructions live in the README but some information is available via GH Wiki. This is not a reason to avoid moving to the wiki, just flagging that docs should be consolidated in the future.

Testing: Following the local druid setup instructions, I can't run `make single_server_up` without volume mounting errors (on macOS, with DRUID_SHARED_FOLDER=/Users/isabel/home/share). I completely pruned docker in case my machine had conflicting volumes from other projects but no dice. I couldn't immediately find a problem in the compose files, so we'll have to check in tomorrow/later this week.

2023-11-09 15:59 UTC, Sybrand commented
> Wiki + README: I consider this an interim state — it's slightly confusing that the majority of the instructions live in the README but some information is available via GH Wiki. This is not a reason to avoid moving to the wiki, just flagging that docs should be consolidated in the future.

Agreed - I think our options are carving off sections bit by bit (like this), or re-writing the whole README into the Wiki in one go. Right now we're carving...

> 
> Testing: Following the local druid setup instructions, I can't run `make single_server_up` without volume mounting errors (on macOS, with DRUID_SHARED_FOLDER=/Users/isabel/home/share). I completely pruned docker in case my machine had conflicting volumes from other projects but no dice. I couldn't immediately find a problem in the compose files, so we'll have to check in tomorrow/later this week.

Could you please give me some details? Or else schedule a call and we'll go over it.

2023-11-09 16:11 UTC, Sybrand commented on db/druid/indexing/common.py
> +def fix_local_path(
`_fix_path_for_druid` make more sense?

2023-11-09 16:22 UTC, Sybrand commented on pipeline/template/index/run/00_druid/00_index
> +  --local_server_shared_folder "${DRUID_SHARED_FOLDER:-/home/share}" \
Sorry, not fully understanding - are you saying make `--task_hash_dir` required?

2023-11-09 16:23 UTC, Sybrand commented on scripts/db/postgres/dev/create_default_admin_user.py
> -    email = 'software@something.com'
The poor people at software.com would start getting strange emails....

2023-11-09 21:23 UTC, tahitihat commented on pipeline/template/index/run/00_druid/00_index
> +  --local_server_shared_folder "${DRUID_SHARED_FOLDER:-/home/share}" \
Yes —

2023-11-09 23:51 UTC, tahitihat commented
Okay, slacking you👍 I don't know exactly when I should schedule a call across our post Daylight Savings time difference. Will PM.

2023-11-14 12:57 UTC, Sybrand commented
> 
> Testing: Following the local druid setup instructions, I can't run `make single_server_up` without volume mounting errors (on macOS, with DRUID_SHARED_FOLDER=/Users/isabel/home/share). I completely pruned docker in case my machine had conflicting volumes from other projects but no dice. I couldn't immediately find a problem in the compose files, so we'll have to check in tomorrow/later this week.

I've just removed the named volumes entirely - it causes too much headaches. Now, with a direct volume mapping, you can change without having to worry about a pesky volume hanging around.

2023-11-14 23:10 UTC, AbbyBeeler commented
@zenenock can you take reviewing this?

2023-11-15 08:42 UTC, zenenock commented
I'll review today

2024-01-04 14:12 UTC, merged